services:
  app.repository.asset:
    class: AppBundle\Repository\AssetRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - AppBundle\Entity\Asset

  app.repository.asset_association:
    class: AppBundle\Repository\AssetAssociationRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - AppBundle\Entity\AssetAssociation
